# Setup
title: Tal Hoffman
url: https://www.talhoffman.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

ga_analytics: UA-173172635-2

author:
  name: Tal Hoffman
  url: https://www.talhoffman.com

version: 3.0.0

nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
